version: 0.2

env:
  variables:
    EC2_TAG_NAME: "fastapi-ec2"
    APP_DIR: "/opt/app"

phases:
  build:
    commands:
      - echo "Finding EC2 instance..."
      - |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=$EC2_TAG_NAME" \
          --query "Reservations[].Instances[].InstanceId" \
          --output text)

        if [ -z "$INSTANCE_ID" ]; then
          echo "EC2 instance not found. Skipping deploy."
          exit 0
        fi

      - echo "Fetching parameters from SSM..."
      - MYSQL_USER=$(aws ssm get-parameter --name /fastapi_app/mysqluser --with-decryption --query Parameter.Value --output text)
      - MYSQL_PASSWORD=$(aws ssm get-parameter --name /fastapi_app/mysqlpasswd --with-decryption --query Parameter.Value --output text)
      - MYSQL_DATABASE=$(aws ssm get-parameter --name /fastapi_app/mysqldb --with-decryption --query Parameter.Value --output text)

      - echo "Deploying image tag: $IMAGE_TAG via deploy.sh"
      - |
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy FastAPI app" \
          --parameters 'commands=[
            "chmod +x '"$APP_DIR"'/deploy.sh",
            "IMAGE_TAG='"$IMAGE_TAG"' MYSQL_USER='"$MYSQL_USER"' MYSQL_PASSWORD='"$MYSQL_PASSWORD"' MYSQL_DATABASE='"$MYSQL_DATABASE"' bash '"$APP_DIR"'/deploy.sh"
          ]'

artifacts:
  files:
    - image.env
