version: 0.2

env:
  variables:
    APP_DIR: "/opt/app"

phases:
  pre_build:
    commands:
      - echo "Listing files in input artifact..."
      - ls -R $CODEBUILD_SRC_DIR
      - echo "Fetching EC2 instance by tag..."
      # Query AWS for EC2 instance ID with the given tag
      - INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=FastAPI-Docker-EC2" "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].InstanceId" --output text)
      - if [ -z "$INSTANCE_ID" ]; then echo "EC2 instance not found. Skipping deploy."; exit 0; fi
      - echo "EC2 instance ID:$INSTANCE_ID"
      - echo "Fetching parameters from SSM..."
      - MYSQL_USER=$(aws ssm get-parameter --name /fastapi_app/nysqluser --with-decryption --query Parameter.Value --output text)
      - MYSQL_PASSWORD=$(aws ssm get-parameter --name /fastapi_app/mysqlpasswd --with-decryption --query Parameter.Value --output text)
      - MYSQL_DATABASE=$(aws ssm get-parameter --name /fastapi_app/mysqldb --with-decryption --query Parameter.Value --output text)
      - DOCKER_USER=$(aws ssm get-parameter --name /fastapi_app/dockeruser --with-decryption --query Parameter.Value --output text)

      # ---------- Read IMAGE_TAG from artifact ----------
      - echo "Reading IMAGE_TAG from artifact..."
      - IMAGE_TAG=$(grep IMAGE_TAG $CODEBUILD_SRC_DIR_1/image.env | cut -d'=' -f2)
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Deploying FastAPI app on EC2 $INSTANCE_ID..."

      # ---------- Copy docker-compose.runtime.yml from artifact and deploy ----------
      - |
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy FastAPI app" \
          --parameters commands="[
            \"mkdir -p $APP_DIR\",
            \"cp $CODEBUILD_SRC_DIR_1/docker-compose.runtime.yml $APP_DIR/docker-compose.runtime.yml\",
            \"cd $APP_DIR\",
            \"echo 'IMAGE_TAG=$IMAGE_TAG' > .env\",
            \"echo 'MYSQL_USER=$MYSQL_USER' >> .env\",
            \"echo 'MYSQL_PASSWORD=$MYSQL_PASSWORD' >> .env\",
            \"echo 'MYSQL_DATABASE=$MYSQL_DATABASE' >> .env\",
            \"echo 'DOCKER_USER=$DOCKER_USER' >> .env\",
            \"docker compose -f docker-compose.runtime.yml pull\",
            \"docker compose -f docker-compose.runtime.yml up -d\"
          ]"

  post_build:
    commands:
      - echo "Deploy stage completed successfully."

artifacts:
  files: []  # Deploy stage does not produce artifacts
