version: 0.2

env:
  variables:
    APP_DIR: "/opt/app"

phases:
  install:
    commands:
      - echo "Installing AWS CLI v2 if not present..."
      - |
        if ! command -v aws &> /dev/null; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        fi

  pre_build:
    commands:
      - echo "Fetching EC2 instance by tag..."
      - INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=FastAPI-Docker-EC2" "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].InstanceId" --output text)
      - if [ -z "$INSTANCE_ID" ]; then echo "EC2 instance not found. Skipping deploy."; exit 0; fi
      - echo "EC2 instance ID:$INSTANCE_ID"
      - echo "Fetching parameters from SSM..."
      - MYSQL_USER=$(aws ssm get-parameter --name /fastapi_app/mysqluser --with-decryption --query Parameter.Value --output text)
      - MYSQL_PASSWORD=$(aws ssm get-parameter --name /fastapi_app/mysqlpasswd --with-decryption --query Parameter.Value --output text)
      - MYSQL_DATABASE=$(aws ssm get-parameter --name /fastapi_app/mysqldb --with-decryption --query Parameter.Value --output text)

  build:
    commands:
      - echo "Deploying FastAPI app on EC2 $INSTANCE_ID..."
      - |
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy FastAPI app" \
          --parameters commands="[
            \"cd $APP_DIR\",
            \"echo IMAGE_TAG=$IMAGE_TAG > .env\",
            \"echo MYSQL_USER=$MYSQL_USER >> .env\",
            \"echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> .env\",
            \"echo MYSQL_DATABASE=$MYSQL_DATABASE >> .env\",
            \"docker compose -f docker-compose.runtime.yml pull\",
            \"docker compose -f docker-compose.runtime.yml up -d\"
          ]"

  post_build:
    commands:
      - echo "Deploy stage completed."

artifacts:
  files:
    - image.env
  optional: true

