version: 0.2

phases:
  build:
    commands:
      - set -x  # shows every command
      - cd infra
      - terraform init
      - terraform plan

  post_build:
    commands:
      - terraform apply -auto-approve
