version: 0.2

env:
  variables:
    EC2_TAG_NAME: "FastAPI-Docker-EC2"
    APP_DIR: "/opt/app"

phases:
  install:
    commands:
      - echo "Installing AWS CLI v2 if not present..."
      - if ! command -v aws &> /dev/null; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
          unzip awscliv2.zip;
          sudo ./aws/install;
        fi

  build:
    commands:
      - echo "Finding EC2 instance by tag..."
      - |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=$EC2_TAG_NAME" \
          --query "Reservations[].Instances[].InstanceId" \
          --output text)

        if [ -z "$INSTANCE_ID" ]; then
          echo "EC2 instance not found. Skipping deploy."
          exit 0
        fi

        echo "Fetching parameters from SSM..."
        MYSQL_USER=$(aws ssm get-parameter --name /fastapi_app/mysqluser --with-decryption --query Parameter.Value --output text)
        MYSQL_PASSWORD=$(aws ssm get-parameter --name /fastapi_app/mysqlpasswd --with-decryption --query Parameter.Value --output text)
        MYSQL_DATABASE=$(aws ssm get-parameter --name /fastapi_app/mysqldb --with-decryption --query Parameter.Value --output text)

        echo "Deploying Docker image tag: $IMAGE_TAG on EC2 $INSTANCE_ID"

        # Execute deploy.sh on EC2 via SSM
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy FastAPI app" \
          --parameters commands="[
            \"chmod +x $APP_DIR/deploy.sh\",
            \"IMAGE_TAG=$IMAGE_TAG MYSQL_USER=$MYSQL_USER MYSQL_PASSWORD=$MYSQL_PASSWORD MYSQL_DATABASE=$MYSQL_DATABASE bash $APP_DIR/deploy.sh\"
          ]" \
          --output text

artifacts:
  files:
    - image.env
