version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.7.7/terraform_1.7.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - echo "Checking if infra/* files changed..."
      - |
        if [[ -z "$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION~1 $CODEBUILD_RESOLVED_SOURCE_VERSION | grep '^infra/')" ]]; then
          echo "No infra changes, skipping Terraform build"
          exit 0
        fi
      - cd infra
      - terraform init
      - terraform plan

  post_build:
    commands:
      - echo "Applying Terraform..."
      - cd infra
      - terraform apply -auto-approve
