version: 0.2

env:
  parameter-store:
    DOCKER_USER: /fastapi_app/dockeruser
    DOCKER_PASS: /fastapi_app/docker_passwd

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Checking Docker"
      - docker --version

  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - docker build -f app/Dockerfile -t "$DOCKER_USER/fastapi-app:$IMAGE_TAG" app/
      - docker tag "$DOCKER_USER/fastapi-app:$IMAGE_TAG" "$DOCKER_USER/fastapi-app:stable"


  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push $DOCKER_USER/fastapi-app:$IMAGE_TAG
      - docker push $DOCKER_USER/fastapi-app:stable
      - echo "IMAGE_TAG=$IMAGE_TAG" > $CODEBUILD_SRC_DIR/image.env

artifacts:
  files:
    - image.env      # This will be uploaded and can be downloaded in deploy stage
    - app/docker-compose.runtime.yml
  discard-paths: yes
  optional: false

