version: 0.2

phases:
  build:
    commands:
      - cd infra
      - terraform init
      - terraform plan -out=tfplan

  post_build:
    commands:
      - cd infra
      - terraform apply -auto-approve tfplan
