version: 0.2

env:
  parameter-store:
    DOCKER_USER: /fastapi_app/dockeruser
    DOCKER_PASS: /fastapi_app/docker_passwd

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USER -p $DOCKER_PASS

  build:
    commands:
      - cd app
      - docker compose -f docker-compose.ci.yml build
      - docker compose -f docker-compose.ci.yml push
